services:
  flask:
    container_name: flask-backend
    build:
      context: ./flask
      args:
        - HOST_VOLUME_PATH=${HOST_VOLUME_PATH}
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
        - DOCKER_GID=${DOCKER_GID}
    environment:
      - ARANGO_DB_URL=http://brondb:8529
      - ARANGO_DB_NAME=BRON
      - ARANGO_DB_USERNAME=root
      - ARANGO_DB_PASSWORD=changeme
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${HOST_VOLUME_PATH}/flask/shared:/shared"
      - "${HOST_VOLUME_PATH}/flask/generatedFiles:/generatedFiles"
      - "${HOST_VOLUME_PATH}/flask/react-app/public/data:/react-app/public/data"
    ports:
      - "5000:5000"
    privileged: true
    networks:
      - ssp_network
  react-app:
    build:
      context: ./flask/react-app
      dockerfile: Dockerfile
    container_name: react-app
    environment:
      - REACT_APP_API_URL=http://flask:5000
    volumes:
      - "${HOST_VOLUME_PATH}/flask/react-app/public/data:/app/public/data"
    ports:
      - "3000:3000"
    networks:
      - ssp_network
  mock-server:
    container_name: mock-server
    build:
      context: ./mock
      dockerfile: Dockerfile
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
    environment:
      - OPA_SERVER_URL=http://opa:8181
      - USE_REAL_OPA=true
    volumes:
      - "${HOST_VOLUME_PATH}/logs:/logs"
    ports:
      - "8000:8000"
    depends_on:
      - opa
    networks:
      - ssp_network
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    volumes:
      - ./policies:/policies/
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "--log-level=debug"
      - "/policies"
    networks:
      - ssp_network
networks:
  ssp_network:
    external: true