version: "3.5"
services:
  driver:
    container_name: driver
    build: ./AttackTechniquesToControls
    network_mode: "host"
  flask:
    container_name: flask-frontend-cli
    build:
      context: ./flask
      args:
        - HOST_VOLUME_PATH=${HOST_VOLUME_PATH}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${HOST_VOLUME_PATH}/flask/shared:/shared"
    network_mode: "host" 
    privileged: true
