version: "3.5"
services:
  #driver:
    #container_name: driver
    #build: ./AttackTechniquesToControls
    #network_mode: "host"
    
    #networks:
      #- ssp_network
  flask:
    container_name: flask-frontend-cli
    build:
      context: ./flask
      args:
        - HOST_VOLUME_PATH=${HOST_VOLUME_PATH}
    environment:
      - ARANGO_DB_URL=http://brondb:8529
      - ARANGO_DB_NAME=BRON
      - ARANGO_DB_USERNAME=root
      - ARANGO_DB_PASSWORD=changeme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${HOST_VOLUME_PATH}/flask/shared:/shared"
      - "${HOST_VOLUME_PATH}/flask/shared:/shared/catalog"
      - "${HOST_VOLUME_PATH}/flask/shared:/shared/profile"
      - "${HOST_VOLUME_PATH}/flask/shared:/shared/ssp"
      - "${HOST_VOLUME_PATH}/flask/ssp:/ssp"
      - "${HOST_VOLUME_PATH}/flask/shared:/shared/component"
      - "${HOST_VOLUME_PATH}/flask/shared:/shared/ap"
      - "${HOST_VOLUME_PATH}/flask/ap:/ap"
    #network_mode: "host" 
    ports:
      - "5000:5000"
    privileged: true
    networks:
      - ssp_network
  react-app:
    build:
      context: ./flask/react-app
      dockerfile: Dockerfile
    container_name: react-app
    environment:
      - REACT_APP_API_URL=http://flask:5000
    #network_mode: "host"
    #volumes:
      #- /var/run/docker.sock:/var/run/docker.sock
      #- "${HOST_VOLUME_PATH}/flask/shared:/shared"
    ports:
      - "3000:3000"
    networks:
      - ssp_network
networks:
  ssp_network:
    external: true