apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: flask-claim6
  name: flask-claim6
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
