apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: react-app
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: react-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: react-app
    spec:
      containers:
        - env:
            - name: REACT_APP_API_URL
              value: http://flask:5000
          image: msusel-ssp-manager_react-app:latest
          imagePullPolicy: Never
          name: react-app
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
