apiVersion: apps/v1
kind: Deployment
metadata:
  name: brondb
  namespace: bron
  labels:
    io.kompose.service: brondb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: brondb
  template:
    metadata:
      labels:
        io.kompose.service: brondb
    spec:
      containers:
        - name: brondb
          image: arangodb:3.8.1
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          ports:
            - containerPort: 8529
          env:
            - name: ARANGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: arango-root-password
                  key: password
            - name: ARANGO_STORAGE_ENGINE
              value: "rocksdb"
            - name: ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY
              value: "4G"
          volumeMounts:
            - name: brondb-data
              mountPath: /var/lib/arangodb3
            - name: brondb-apps-data
              mountPath: /var/lib/arangodb3-apps
          readinessProbe:
            httpGet:
              path: /
              port: 8529
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: brondb-data
          persistentVolumeClaim:
            claimName: brondb-data-container
        - name: brondb-apps-data
          persistentVolumeClaim:
            claimName: brondb-apps-data-container
