apiVersion: v1
kind: Service
metadata:
  name: brondb
  namespace: bron
  labels:
    io.kompose.service: brondb
spec:
  type: NodePort
  ports:
    - name: "8529"
      port: 8529
      targetPort: 8529
      nodePort: 30529  # Static port on the node
  selector:
    io.kompose.service: brondb
