apiVersion: v1
kind: Service
metadata:
  name: brondb
  namespace: bron
  labels:
    io.kompose.service: brondb
spec:
  ports:
    - name: "8529"
      port: 8529
      targetPort: 8529
  selector:
    io.kompose.service: brondb
