apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brondb-data-container
  namespace: bron
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: brondb-data-pv
