apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: brondb
  name: brondb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: brondb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: brondb
    spec:
      containers:
        - env:
            - name: ARANGO_ROOT_PASSWORD_FILE
              value: /run/secrets/arango-root-password
          image: arangodb:3.8.1
          name: brondb
          ports:
            - containerPort: 8529
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets
              name: arango-root-password
              subPath: arango-root-password
            - mountPath: /var/lib/arangodb3
              name: brondb-data-container
            - mountPath: /var/lib/arangodb3-apps
              name: brondb-apps-data-container
      restartPolicy: Always
      volumes:
        - name: arango-root-password
          secret:
            items:
              - key: arango-root-password
                path: arango-root-password
            secretName: arango-root-password
        - name: brondb-data-container
          persistentVolumeClaim:
            claimName: brondb-data-container
        - name: brondb-apps-data-container
          persistentVolumeClaim:
            claimName: brondb-apps-data-container
