apiVersion: v1
kind: PersistentVolume
metadata:
  name: brondb-data-pv
  namespace: bron
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/arangodb3
    type: DirectoryOrCreate
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: brondb-apps-data-pv
  namespace: bron
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/arangodb3-apps
    type: DirectoryOrCreate
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bootstrap-data-pv
  namespace: bron
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate
  storageClassName: standard