apiVersion: batch/v1
kind: Job
metadata:
  name: driver
  namespace: bron
spec:
  backoffLimit: 4
  activeDeadlineSeconds: 1800  # 30 minutes timeout
  template:
    metadata:
      labels:
        app: driver
    spec:
      containers:
      - name: driver
        image: msusel-ssp-manager-driver:latest
        imagePullPolicy: Never
        env:
          - name: ARANGO_DB_URL
            value: http://brondb:8529
          - name: ARANGO_DB_NAME
            value: BRON
          - name: ARANGO_DB_USERNAME
            value: root
          - name: ARANGO_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: arango-root-password
                key: password
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until wget -q --spider http://brondb:8529/_api/version; do echo waiting for brondb; sleep 2; done;']
      restartPolicy: OnFailure
