apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flask
  template:
    metadata:
      labels:
        io.kompose.service: flask
    spec:
      securityContext:
        fsGroup: 1001    # Moved to pod-level security context
      containers:
        - name: flask-backend
          image: msusel-ssp-manager-flask:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /shared
              name: flask-shared
            - mountPath: /generatedFiles
              name: flask-generated
            - mountPath: /var/run/docker.sock
              name: docker-sock
          env:
            - name: HOST_VOLUME_PATH
              value: "/flask"
          securityContext:
            privileged: true
            runAsUser: 1000  # This should match your appuser UID
            runAsGroup: 1001  # This should match your docker group GID
      volumes:
        - name: flask-shared
          persistentVolumeClaim:
            claimName: flask-shared-claim
        - name: flask-generated
          persistentVolumeClaim:
            claimName: flask-generated-claim
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
