apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flask
  template:
    metadata:
      labels:
        io.kompose.service: flask
    spec:
      containers:
        - name: flask-backend
          image: ghcr.io/${{ env.GITHUB_USER_LOWERCASE }}/msu-ssp-manager-flask:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /shared
              name: flask-shared
            - mountPath: /generatedFiles
              name: flask-generated
          env:
            - name: HOST_VOLUME_PATH
              value: "/flask"
            - name: ARANGO_DB_URL
              value: "http://brondb:8529"
            - name: ARANGO_DB_NAME
              value: "BRON"
            - name: ARANGO_DB_USERNAME
              value: "root"
            - name: ARANGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: arango-root-password
                  key: arango-root-password
            - name: GITHUB_ACTOR
              valueFrom:
                configMapKeyRef:
                  name: github-config
                  key: github_actor
      volumes:
        - name: flask-shared
          persistentVolumeClaim:
            claimName: flask-shared-claim
        - name: flask-generated
          persistentVolumeClaim:
            claimName: flask-generated-claim
