apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-shared-pv
  namespace: bron 
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /flask/shared
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-generated-pv
  namespace: bron 
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /flask/generatedFiles
  storageClassName: standard
