apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000     # Changed from 80 to match Flask's port
      targetPort: 5000
  selector:
    io.kompose.service: flask
