apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flask
  template:
    metadata:
      labels:
        io.kompose.service: flask
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: flask-backend
          image: ghcr.io/ernestoortiz3/msu-ssp-manager-flask:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /shared
              name: flask-shared
            - mountPath: /generatedFiles
              name: flask-generated
          env:
            - name: FLASK_APP
              value: "run:create_app"
            - name: FLASK_ENV
              value: "production"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: flask-secrets
                  key: secret-key
            - name: UPLOAD_FOLDER
              value: "/shared"
            - name: GENERATION_FOLDER
              value: "/generatedFiles"
            - name: HOST_VOLUME_PATH
              value: "/flask"
            - name: ARANGO_DB_URL
              value: "http://brondb:8529"
            - name: ARANGO_DB_NAME
              value: "BRON"
            - name: ARANGO_DB_USERNAME
              value: "root"
            - name: ARANGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: arango-root-password
                  key: arango-root-password
      volumes:
        - name: flask-shared
          persistentVolumeClaim:
            claimName: flask-shared-claim
        - name: flask-generated
          persistentVolumeClaim:
            claimName: flask-generated-claim
