apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: opa
  name: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opa
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: opa
    spec:
      containers:
        - args:
            - run
            - --server
            - --addr=0.0.0.0:8181
            - --log-level=debug
            - /policies
          image: openpolicyagent/opa:latest
          name: opa
          ports:
            - containerPort: 8181
              protocol: TCP
          volumeMounts:
            - mountPath: /policies/authentication.rego
              subPath: authentication.rego
              name: opa-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: opa-cm0
          name: opa-cm0
