apiVersion: v1
kind: PersistentVolume
metadata:
  name: oscal-shared-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/oscal-shared
  storageClassName: standard