apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: react-app
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: react-app
  template:
    metadata:
      labels:
        io.kompose.service: react-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: react-app
          image: ghcr.io/ernestoortiz3/msu-ssp-manager-react-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://flask.default.svc.cluster.local"
      restartPolicy: Always
