apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: react-app
  name: react-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Changed from 3000 to 80 to match nginx
  selector:
    io.kompose.service: react-app
