apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"  # Makes this an external load balancer
  labels:
    io.kompose.service: react-app
  name: react-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    io.kompose.service: react-app
