apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: react-app
  name: react-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    io.kompose.service: react-app
