apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: react-app
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: react-app
  template:
    metadata:
      labels:
        io.kompose.service: react-app
    spec:
      containers:
        - env:
            - name: REACT_APP_API_URL
              value: "http://flask.default.svc.cluster.local"  # Using K8s DNS name
          image: ghcr.io/${{ format('{0}', github.actor) }}/msu-ssp-manager-react-app:latest
          imagePullPolicy: Always
          name: react-app
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
