apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: bron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: msusel-ssp-manager_react-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
          - name: REACT_APP_API_URL
            value: "http://flask:5000"
