name: Deploy to AKS

on:
  push:
    branches: 
      - minikube
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "GITHUB_USER_LOWERCASE=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build OSCAL Processing image
        run: |
          docker build \
            -t ghcr.io/${{ env.GITHUB_USER_LOWERCASE }}/oscal-processing:latest \
            ./oscal-processing
          docker push ghcr.io/${{ env.GITHUB_USER_LOWERCASE }}/oscal-processing:latest

      - name: Build Flask image
        run: |
          docker build \
            --build-arg HOST_VOLUME_PATH="/flask" \
            -t ghcr.io/${{ env.GITHUB_USER_LOWERCASE }}/msu-ssp-manager-flask:latest \
            -f flask/Dockerfile ./flask
          docker push ghcr.io/${{ env.GITHUB_USER_LOWERCASE }}/msu-ssp-manager-flask:latest

      - name: Build React image
        run: |
          docker build \
            -t ghcr.io/${{ env.GITHUB_USER_LOWERCASE }}/msu-ssp-manager-react-app:latest \
            ./react-app
          docker push ghcr.io/${{ env.GITHUB_USER_LOWERCASE }}/msu-ssp-manager-react-app:latest
