name: Minikube CI/CD

on:
  push:
    branches:
      - minikube

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      
      - name: Build and push Docker images
        run: |
          docker build -t ghcr.io/${{ github.actor }}/msu-ssp-manager-flask:latest -f msu-ssp-manager-flask/Dockerfile ./msu-ssp-manager-flask
          docker push ghcr.io/${{ github.actor }}/msu-ssp-manager-flask:latest
          docker build -t ghcr.io/${{ github.actor }}/msu-ssp-manager-react-app:latest -f msu-ssp-manager-react-app/Dockerfile ./msu-ssp-manager-react-app
          docker push ghcr.io/${{ github.actor }}/msu-ssp-manager-react-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Kubectl
        run: |
          echo "${{ secrets.KUBECONFIG_SECRET }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig
          
          # Apply Flask-related manifests
          kubectl apply -f manifests/flask-shared-pv.yaml
          kubectl apply -f manifests/flask-pvc.yaml
          kubectl apply -f manifests/flask-deployment.yaml
          kubectl apply -f manifests/flask-service.yaml
          
          # Apply React-app manifests
          kubectl apply -f manifests/react-app-deployment.yaml
          kubectl apply -f manifests/react-app-service.yaml
          
          # Restart deployments
          kubectl rollout restart deployment msu-ssp-manager-flask -n default
          kubectl rollout restart deployment msu-ssp-manager-react-app -n default